# Generated by Django 5.0.1 on 2024-01-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
